# Generated by Django 4.1.1 on 2023-01-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarocket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status_message',
            field=models.TextField(blank=True),
        ),
    ]
