# Generated by Django 4.1.5 on 2023-01-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarocket', '0002_alter_batch_status_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push',
            name='json_file',
            field=models.FileField(upload_to='temp/'),
        ),
    ]
