# Generated by Django 4.1.5 on 2023-01-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarocket', '0003_alter_push_json_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
