# Generated by Django 4.1.5 on 2023-01-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarocket', '0004_batch_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
