# Generated by Django 4.1.5 on 2023-01-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarocket', '0006_customuser_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_plan_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_plan_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
